.TH "server_start" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_start \- server_start 
Inicia el servidor (TCP)
.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_server\&.h\fP>\fP 
.br
 \fBint\fP \fBserver_start\fP \fB\fP() \fP 
.SH "Descripción"
.PP
Inicializa el socket principal del servidor, para ello se genera una llamada a \fBsocket()\fP para iniciar el socket\&. A dicha función se le pasan como parámetros valores adecuados para la inicialización: 
.PD 0

.IP "\(bu" 2
AF_INET 
.IP "\(bu" 2
SOCK_STREAM 
.PP
Tras generar el identificador del socket con la llamada anterior, se asignan parámetros adicionales (como SOL_SOCKET y SO_REUSEADDR), además se genera la estructura sockaddr_in de dirección, en la que se especifican ciertos parámetros: 
.PD 0

.IP "\(bu" 2
\fBsin_family:\fP Se indica que la conexión es TCP/IP\&. 
.IP "\(bu" 2
\fBsin_port:\fP Se indica que el puerto por defecto es 6667\&. 
.IP "\(bu" 2
\fBsin_addr:\fP Se indica que cualquier IP es admitida al conectar (INADDR_ANY)\&. 
.PP
Tras generar la configuración básica del socket, se utilizan las funciones bind() y listen() para finalizar con la conexión del socket principal al que accederán los clientes mediante el puerto por defecto: 
.PD 0

.IP "\(bu" 2
\fBbind():\fP Realiza una unión entre el identificador del socket generado y el struct de Direccion mencionado anteriormente para asignar los parametros del struct a ese socket\&. 
.IP "\(bu" 2
\fBlisten():\fP Indica al socket que debe admitir conexiones en el identificador del socket generado anteriormente y además le pasa el parámetros de conexiones máximas que en este caso está fijado por MAX_CONNECTIONS (100)\&. 
.PP
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBint\fP Descriptor del master socket generado para atender las peticiones\&. 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

