.TH "server_command_names" 3 "Lunes, 13 de Marzo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_command_names \- server_command_names 
Función handler del comando NAMES del IRC\&.
.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_function_handlers\&.h\fP>\fP 
.br
 \fBvoid \fBserver_command_names(char* command, int desc, char * nick_static, int* register_status)\fP\fP \fP 
.SH "Descripción"
.PP
Esta función ejecuta el handler del comando en cuestión, para ello realiza una serie de comprobaciones previas:
.PP
.PD 0
.IP "\(bu" 2
\fBParse:\fP Comprueba que el parseo del comando NAMES sea correcto\&. 
.PP
.PP
Una vez realizadas las comprobaciones, dicha función se ejecuta con el siguiente flujo:
.PP
.PD 0
.IP "\(bu" 2
\fBLista de usuarios del canal:\fP Se solicita la lista de usuarios en el canal mediante la función del TAD \fBIRCTAD_ListNicksOnChannelArray\fP\&. Se devuelven todos los usuarios del canal comprobando además el modo del usuario en dicho canal, en caso de ser el operador se coloca un @ al comienzo del nombre\&.  
.IP "\(bu" 2
\fBMensaje final:\fP Se envía un mensaje de confirmación al usuario para indicarle de que se ha finalizado el envío de la lista de usuarios del canal mediante la función del TAD \fBIRCMsg_RplEndOfNames\fP\&.  
.PP
.PP
Al finalizar el flujo de la función se liberan los recursos utilizados\&.
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBvoid\fP No devuelve nada\&. 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

