.TH "server_channels_update_away" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_channels_update_away \- server_channels_update_away 
Actualiza el mensaje away de un usuario\&.
.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_common_functions\&.h\fP>\fP 
.br
 \fBint \fBserver_channels_update_away(char* nick, char* away)\fP\fP \fP 
.SH "Descripción"
.PP
Actualiza el mensaje away de un usuario mediante la función del TAD \fBIRCTADUser_SetAway\fP para actualizar los away de los usuarios mediante el parámetro recibido \fBchar *away\fP\&. 
.PP
Comprueba previamente que el usuario exista mediante la función \fBIRCTADUser_GetData\fP utilizando el parámetro recibido \fBchar *nick\fP\&.
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBint\fP Devuelve valor verdado/falso dependiendo de la búsqueda\&. 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

