.TH "server_start_communication" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_start_communication \- server_start_communication 
Ejecuta el control (main) principal para cada hilo\&.
.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_server\&.h\fP>\fP 
.br
 \fBvoid *server_start_communication(int socket_desc)\fP \fP 
.SH "Descripción"
.PP
Contiene el código que ejecutan los hijos al recibir la conexión de un cliente en \fB\fBserver_accept_connection()\fP\fP\&. Declara varias variables que se pasan como parámetros al resto de funciones utilizadas para el parseo de comandos:
.PP
.PD 0
.IP "\(bu" 2
\fBchar *nick:\fP Almacena el nick del personaje, se reserva memoria y se pasa como puntero a las funciones de parseo de comandos en la que la función destinada al comando nick utilizará un \fBstrcpy\fP para actualizar dicho valor\&. 
.IP "\(bu" 2
\fBint *register_status:\fP Entero que representa el estado actual del cliente del hilo, sirve de control para las funciones de parseo y cierre de socket: 
.PD 0

.IP "  \(bu" 4
0: Indica que no se ha efectuado un registro válido del usuario (comando NICK y USER)\&. 
.IP "  \(bu" 4
1: Indica que se ha parseado correctamente el nick y es posible realizar el registro del usuario (comando USER)\&. 
.IP "  \(bu" 4
2: Indica que se ha registrado correctamente usuario y es posible realizar cualquier otro comando del IRC\&. Sirve de control para no ejecutar otros comandos hasta que el usuario no envíe los comandos válidos (NICK y USER) para el registro\&. A su vez, esto permitirá que en caso de cerrarse el socket se comprobará que si el valor de esta variable es 2 se utilizará la función del TAD para eliminar al usuario de la lista\&. 
.PP

.PP
.PP
Contiene un bucle que comprueba si el socket sigue abierto y parsea los comandos del usuario mediante las funciones apropiadas para ello (\fBIRC_UnPipelineCommands y IRC_CommandQuery\fP)\&. Dichos comandos parseados envían a la función \fBserver_execute_function\fP que contiene un array de punteros a función para redirigir cada comando a su función apropiada\&.
.PP
Una vez se detecta que el socket se ha cerrado, se elimina al usuario del TAD en caso de que \fBregister_status\fP tenga el valor adecuado (2) y se liberan los punteros reservados para este hilo\&.
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBvoid\fP No devuelve nada\&. 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

