.TH "server_command_privmsg" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_command_privmsg \- server_command_privmsg 
Función handler del comando PRIVMSG del IRC\&.
.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_function_handlers\&.h\fP>\fP 
.br
 \fBvoid \fBserver_command_privmsg(char* command, int desc, char * nick_static, int* register_status)\fP\fP \fP 
.SH "Descripción"
.PP
Esta función ejecuta el handler del comando en cuestión, para ello realiza una serie de comprobaciones previas:
.PP
.PD 0
.IP "\(bu" 2
\fBParse:\fP Comprueba que el parseo del comando PRIVMSG sea correcto\&. 
.PP
.PP
Una vez realizadas las comprobaciones, dicha función se ejecuta con el siguiente flujo:
.PP
.PD 0
.IP "\(bu" 2
\fBSi el objetivo es un canal:\fP Si el objetivo del mensaje es un canal se recupera la lista de usuarios de dicho canal mediante la función del TAD \fBIRCTAD_ListNicksOnChannelArray\fP y se envía el mensaje a todos los usuarios de dicho canal exceptuando al usuario que envía el mensaje\&.  
.IP "\(bu" 2
\fBSi el objetivo es un usuario:\fP Si el objetivo del mensaje es un usuario se envía un mensaje al usuario destinatario (target) recuperando su información mediante la función del TAD \fBIRCTADUser_GetData\fP\&. Se comprueba si el usuario al que se desea enviar el mensaje está \fBAWAY\fP con la función del TAD \fBIRCTADUser_GetAway\fP, en caso afirmativo se devuelve un mensaje al usuario que envía el mensaje informándole de que el usuario destinatario está ausente\&.  
.PP
.PP
Al finalizar el flujo de la función se liberan los recursos utilizados\&.
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBvoid\fP No devuelve nada\&. 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

