.TH "task_t" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <G\-2313\-06\-P1_thread_pool\&.h>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "int \fBarg\fP"
.br
.ti -1c
.RI "void *(* \fBtask_callback\fP )(int \fBarg\fP)"
.br
.ti -1c
.RI "struct \fBlist_head\fP \fBentry\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 28 del archivo G\-2313\-06\-P1_thread_pool\&.h\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "int task_t::arg"

.PP
Definición en la línea 30 del archivo G\-2313\-06\-P1_thread_pool\&.h\&.
.SS "struct \fBlist_head\fP task_t::entry"

.PP
Definición en la línea 32 del archivo G\-2313\-06\-P1_thread_pool\&.h\&.
.SS "void*(* task_t::task_callback) (int \fBarg\fP)"

.PP
Definición en la línea 31 del archivo G\-2313\-06\-P1_thread_pool\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes de Comunicaciones II del código fuente\&.
