.TH "Referencia del directorio includes" 3 "Lunes, 8 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio includes \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG\-2313\-06\-P2_client\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG\-2313\-06\-P2_client_common_functions\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG\-2313\-06\-P2_client_err_handlers\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG\-2313\-06\-P2_client_function_handlers\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG\-2313\-06\-P2_files\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG\-2313\-06\-P2_tcp\&.h\fP"
.br
.in -1c
