.TH "Referencia del directorio srclib" 3 "Lunes, 8 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio srclib \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG\-2313\-06\-P2_files\&.c\fP"
.br
.ti -1c
.RI "archivo \fBG\-2313\-06\-P2_tcp\&.c\fP"
.br
.in -1c
