.TH "Referencia del directorio includes" 3 "Lunes, 13 de Marzo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio includes \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG-2313-06-P1_common_functions\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG-2313-06-P1_function_handlers\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG-2313-06-P1_list\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG-2313-06-P1_server\&.h\fP"
.br
.ti -1c
.RI "archivo \fBG-2313-06-P1_thread_pool\&.h\fP"
.br
.in -1c
