.TH "client_execute_in_function" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_execute_in_function \- Parseo de entradas 

.SH "Synopsis"
.PP
.PP
.nf
#include <G-2313-06-P3_ssl\&.h>

void client_execute_in_function(long functionName, char* command);
.fi
.PP
 
.SH "Descripción"
.PP
Recibe como parámetro un mensaje desfragmentado y lo pasa por un array de punteros a función a la función correspondiente\&. En caso de no tener ninguna función disponible para el comando se le enviará a la función por defecto\&. 
.br
.SS "Listado de comandos parseados:"
.PP
.PP
.nf
functions[[NICK]             = &server_in_command_nick;
functions[[JOIN]             = &server_in_command_join;
functions[[PART]             = &server_in_command_part;
functions[[MODE]             = &server_in_command_mode;
functions[[TOPIC]            = &server_in_command_topic;
functions[[KICK]             = &server_in_command_kick;
functions[[PRIVMSG]          = &server_in_command_privmsg;
functions[[PING]             = &server_in_command_ping;
functions[[PONG]             = &server_in_command_pong;
.fi
.PP
 
.br
.SS "Listado de respuestas parseadas:"
.PP
.PP
.nf
functions[[RPL_WELCOME]      = &server_in_command_rpl_welcome;
functions[[RPL_CREATED]      = &server_in_command_rpl_created;
functions[[RPL_YOURHOST]     = &server_in_command_rpl_yourhost;
functions[[RPL_LUSERCLIENT]  = &server_in_command_rpl_luserclient;
functions[[RPL_LUSERME]      = &server_in_command_rpl_luserme;
functions[[RPL_MOTDSTART]    = &server_in_command_rpl_motdstart;
functions[[RPL_MOTD]         = &server_in_command_rpl_motd;
functions[[RPL_ENDOFMOTD]    = &server_in_command_rpl_endofmotd;
functions[[RPL_WHOREPLY]     = &server_in_command_rpl_whoreply;
functions[[RPL_AWAY]         = &server_in_command_rpl_away;
functions[[RPL_NOWAWAY]      = &server_in_command_rpl_nowaway;
functions[[RPL_TOPIC]        = &server_in_command_rpl_topic;
functions[[RPL_NOTOPIC]      = &server_in_command_rpl_notopic;
functions[[RPL_YOUREOPER]    = &server_in_command_rpl_youroper;
functions[[RPL_LUSEROP]      = &server_in_command_rpl_luserop;
functions[[RPL_LUSERCHANNELS]= &server_in_command_rpl_luserchannels;
functions[[RPL_YOURESERVICE] = &server_in_command_rpl_youreservice;
functions[[RPL_MYINFO]       = &server_in_command_rpl_myinfo;
functions[[RPL_ENDOFWHO]     = &server_in_command_rpl_endofwho;
functions[[RPL_ENDOFWHOIS]   = &server_in_command_rpl_endofwhois;
functions[[RPL_INFO]         = &server_in_command_rpl_info;
functions[[RPL_WHOISUSER]    = &server_in_command_rpl_whoisuser;
functions[[RPL_WHOISCHANNELS]= &server_in_command_rpl_whoischannels;
functions[[RPL_WHOISOPERATOR]= &server_in_command_rpl_whoisoperator;
functions[[RPL_WHOISSERVER]  = &server_in_command_rpl_whoisserver;
functions[[RPL_WHOISIDLE]    = &server_in_command_rpl_whoisidle;
functions[[RPL_CHANNELMODEIS]= &server_in_command_rpl_channelmodeis;
functions[[RPL_ENDOFNAMES]   = &server_in_command_rpl_endofnames;
functions[[RPL_LIST]         = &server_in_command_rpl_list;
functions[[RPL_LISTEND]      = &server_in_command_rpl_listend;
functions[[RPL_NAMREPLY]     = &server_in_command_rpl_namreply;
.fi
.PP
 
.br
.SS "Listado de errores parseados:"
.PP
.PP
.nf
functions[[ERR_CANNOTSENDTOCHAN]       = &server_in_command_err_cannotsendtochan;
functions[[ERR_ALREADYREGISTRED]       = &server_in_command_err_alreadyregistred;
functions[[ERR_NONICKNAMEGIVEN]        = &server_in_command_err_nonicknamegiven;
functions[[ERR_ERRONEUSNICKNAME]       = &server_in_command_err_erroneusnickname;
functions[[ERR_NICKNAMEINUSE]          = &server_in_command_err_nicknameinuse;
functions[[ERR_NICKCOLLISION]          = &server_in_command_err_nickcollision;
functions[[ERR_UNAVAILRESOURCE]        = &server_in_command_err_unavailresource;
functions[[ERR_RESTRICTED]             = &server_in_command_err_restricted;
functions[[ERR_PASSWDMISMATCH]         = &server_in_command_err_passwdmismatch;
functions[[ERR_BANNEDFROMCHAN]         = &server_in_command_err_bannedfromchan;
functions[[ERR_CHANNELISFULL]          = &server_in_command_err_channelisfull;
functions[[ERR_CHANOPRIVSNEEDED]       = &server_in_command_err_chanoprivsneeded;
functions[[ERR_INVITEONLYCHAN]         = &server_in_command_err_inviteonlychan;
functions[[ERR_NOCHANMODES]            = &server_in_command_err_nochanmodes;
functions[[ERR_NOSUCHCHANNEL]          = &server_in_command_err_nosuchchannel;
functions[[ERR_UNKNOWNMODE]            = &server_in_command_err_unknownmode;
functions[[ERR_NOMOTD]                 = &server_in_command_err_nomotd;
functions[[ERR_NOSUCHNICK]             = &server_in_command_err_nosuchnick;
.fi
.PP
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBvoid\fP No devuelve nada 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

