.TH "src/G-2313-06-P2_client_common_functions.c" 3 "Lunes, 8 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/G-2313-06-P2_client_common_functions.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/G\-2313\-06\-P2_client_common_functions\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void * \fBclient_function_ping\fP (void *arg)"
.br
.ti -1c
.RI "void * \fBclient_function_response\fP (void *arg)"
.br
.ti -1c
.RI "void \fBclient_show_error\fP (char *msg)"
.br
.ti -1c
.RI "void \fBclient_show_error_main\fP (char *msg)"
.br
.ti -1c
.RI "void \fBclient_pre_in_function\fP (char *command)"
.br
.ti -1c
.RI "void \fBclient_execute_in_function\fP (long functionName, char *command)"
.br
.ti -1c
.RI "void \fBclient_pre_out_function\fP (char *command)"
.br
.ti -1c
.RI "void \fBclient_execute_out_function\fP (long functionName, char *command)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBsocket_desc\fP"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "void client_execute_in_function (long functionName, char * command)"

.PP
Definición en la línea 420 del archivo G\-2313\-06\-P2_client_common_functions\&.c\&.
.SS "void client_execute_out_function (long functionName, char * command)"

.PP
Definición en la línea 582 del archivo G\-2313\-06\-P2_client_common_functions\&.c\&.
.SS "void* client_function_ping (void * arg)"

.PP
Definición en la línea 192 del archivo G\-2313\-06\-P2_client_common_functions\&.c\&.
.SS "void* client_function_response (void * arg)"

.PP
Definición en la línea 244 del archivo G\-2313\-06\-P2_client_common_functions\&.c\&.
.SS "void client_pre_in_function (char * command)"

.PP
Definición en la línea 323 del archivo G\-2313\-06\-P2_client_common_functions\&.c\&.
.SS "void client_pre_out_function (char * command)"

.PP
Definición en la línea 528 del archivo G\-2313\-06\-P2_client_common_functions\&.c\&.
.SS "void client_show_error (char * msg)"

.PP
Definición en la línea 274 del archivo G\-2313\-06\-P2_client_common_functions\&.c\&.
.SS "void client_show_error_main (char * msg)"

.PP
Definición en la línea 284 del archivo G\-2313\-06\-P2_client_common_functions\&.c\&.
.SH "Documentación de las variables"
.PP 
.SS "int socket_desc"

.PP
Definición en la línea 4 del archivo G\-2313\-06\-P2_client\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes de Comunicaciones II del código fuente\&.
