.TH "includes/G-2313-06-P2_files.h" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2313-06-P2_files.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <syslog\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <strings\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <redes2/irc\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <net/if\&.h>\fP
.br
\fC#include <ifaddrs\&.h>\fP
.br
\fC#include <redes2/ircxchat\&.h>\fP
.br
\fC#include 'G\-2313\-06\-P2_tcp\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBsrecv\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "void * \fBserver_especial_enviar_ficheros\fP (void *vrecv)"
.br
.ti -1c
.RI "void * \fBserver_especial_recibir_ficheros\fP (void *vmsg)"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "void* server_especial_enviar_ficheros (void * vrecv)"

.PP
Definición en la línea 6 del archivo G\-2313\-06\-P2_files\&.c\&.
.SS "void* server_especial_recibir_ficheros (void * vmsg)"

.PP
Definición en la línea 122 del archivo G\-2313\-06\-P2_files\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes de Comunicaciones II del código fuente\&.
