.TH "group4" 3 "Domingo, 12 de Marzo de 2017" "Version 1.0" "Practica 1 (Servidor IRC) | Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group4 \- The Fourth Group
.PP
Inicia el servidor (TCP)  
Inicia el servidor (TCP) 


.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_server\&.h\fP>\fP 
.br
 \fBint\fP \fBserver_start\fP \fB\fP() \fP 
.SH "Descripción"
.PP
Inicializa el socket
.PP
\fBDevuelve:\fP
.RS 4
\fBint\fP Descriptor del master socket generado para atender las peticiones\&.
.RE
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica 1 (Servidor IRC) | Redes de Comunicaciones II del código fuente\&.
