.TH "server_command_kick" 3 "Lunes, 13 de Marzo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_command_kick \- server_command_kick 
Función handler del comando KICK del IRC\&.
.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_function_handlers\&.h\fP>\fP 
.br
 \fBvoid \fBserver_command_kick(char* command, int desc, char * nick_static, int* register_status)\fP\fP \fP 
.SH "Descripción"
.PP
Esta función ejecuta el handler del comando en cuestión, para ello realiza una serie de comprobaciones previas:
.PP
.PD 0
.IP "\(bu" 2
\fBParse:\fP Comprueba que el parseo del comando KICK sea correcto\&. 
.PP
.PP
Una vez realizadas las comprobaciones, dicha función se ejecuta con el siguiente flujo:
.PP
.PD 0
.IP "\(bu" 2
\fBModo del usuario en el canal:\fP Se comprueba los permisos del usuario para verificar que sea el operador del canal, en caso afirmativo se procede a expulsar al usuario destinatario del kick mediante la función del TAD \fBIRCTAD_KickUserFromChannel\fP\&. En caso de que no sea operador, se devuelve al usuario un mensaje de error generado por la función del TAD \fBIRCMsg_ErrChanOPrivsNeeded\fP\&.  
.IP "\(bu" 2
\fBMensaje final:\fP Se envía un mensaje de confirmación al usuario para indicarle de que se ha realizado la expulsión de forma correcta mediante la función del TAD \fBIRCMsg_Kick\fP\&.  
.PP
.PP
Al finalizar el flujo de la función se liberan los recursos utilizados\&.
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBvoid\fP No devuelve nada\&. 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

