.TH "srecv" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srecv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <G\-2313\-06\-P2_files\&.h>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "char * \fBnick\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "long unsigned \fBlength\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 29 del archivo G\-2313\-06\-P2_files\&.h\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "char* srecv::data"

.PP
Definición en la línea 32 del archivo G\-2313\-06\-P2_files\&.h\&.
.SS "char* srecv::filename"

.PP
Definición en la línea 31 del archivo G\-2313\-06\-P2_files\&.h\&.
.SS "long unsigned srecv::length"

.PP
Definición en la línea 33 del archivo G\-2313\-06\-P2_files\&.h\&.
.SS "char* srecv::nick"

.PP
Definición en la línea 30 del archivo G\-2313\-06\-P2_files\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes de Comunicaciones II del código fuente\&.
