.TH "includes/G-2313-06-P1_function_handlers.h" 3 "Lunes, 13 de Marzo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2313-06-P1_function_handlers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <syslog\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <strings\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <redes2/irc\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include 'G-2313-06-P1_common_functions\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBserver_command_nick\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_user\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_join\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_quit\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_ping\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_list\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_privmsg\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_part\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_names\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_kick\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_mode\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_away\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_whois\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_topic\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.ti -1c
.RI "void \fBserver_command_motd\fP (char *command, int desc, char *nick_static, int *register_status)"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "void server_command_away (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 1001 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_join (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 255 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_kick (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 786 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_list (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 472 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_mode (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 879 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_motd (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 1265 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_names (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 711 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_nick (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 82 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_part (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 644 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_ping (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 407 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_privmsg (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 542 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_quit (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 355 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_topic (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 1186 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_user (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 179 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SS "void server_command_whois (char * command, int desc, char * nick_static, int * register_status)"

.PP
Definición en la línea 1061 del archivo G-2313-06-P1_function_handlers\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes de Comunicaciones II del código fuente\&.
