.TH "server_commands" 3 "Lunes, 13 de Marzo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_commands \- Comandos 
Esta sección incluye las funciones de comandos utilizadas para parsear los comandos recibidos del IRC\&. A estas funciones accede el array de punteros a función descrito en \fBserver_execute_function\fP\&.
.SH "Cabeceras"
.PP
\fC \fB#include\fP \fB<G-2313-06-P1_function_handlers\&.h\&.h>\fP \fP 
.SH "Funciones implementadas"
.PP
Se incluyen las siguientes funciones: 
.PD 0

.IP "\(bu" 2
\fBserver_command_nick\fP 
.IP "\(bu" 2
\fBserver_command_user\fP 
.IP "\(bu" 2
\fBserver_command_join\fP 
.IP "\(bu" 2
\fBserver_command_quit\fP 
.IP "\(bu" 2
\fBserver_command_ping\fP 
.IP "\(bu" 2
\fBserver_command_list\fP 
.IP "\(bu" 2
\fBserver_command_privmsg\fP 
.IP "\(bu" 2
\fBserver_command_part\fP 
.IP "\(bu" 2
\fBserver_command_names\fP 
.IP "\(bu" 2
\fBserver_command_kick\fP 
.IP "\(bu" 2
\fBserver_command_mode\fP 
.IP "\(bu" 2
\fBserver_command_away\fP 
.IP "\(bu" 2
\fBserver_command_whois\fP 
.IP "\(bu" 2
\fBserver_command_topic\fP 
.IP "\(bu" 2
\fBserver_command_motd\fP 
.PP

