.TH "server_users_find_by_nick" 3 "Lunes, 13 de Marzo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_users_find_by_nick \- server_users_find_by_nick 
Busca un usuario por un nick dado\&.
.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_common_functions\&.h\fP>\fP 
.br
 \fBint \fBserver_users_find_by_nick(char* data)\fP\fP \fP 
.SH "Descripción"
.PP
Utiliza la función \fBIRCTADUser_GetData\fP del TAD para buscar un usuario que cumpla las características de nick recibidas como parámetro \fBchar *data\fP\&. Devuelve un valor booleano\&.
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBint\fP Devuelve valor verdado/falso dependiendo de la búsqueda\&. 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

