.TH "server_command_list" 3 "Lunes, 13 de Marzo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_command_list \- server_command_list 
Función handler del comando LIST del IRC\&.
.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P1_function_handlers\&.h\fP>\fP 
.br
 \fBvoid \fBserver_command_list(char* command, int desc, char * nick_static, int* register_status)\fP\fP \fP 
.SH "Descripción"
.PP
Esta función ejecuta el handler del comando en cuestión, para ello realiza una serie de comprobaciones previas:
.PP
.PD 0
.IP "\(bu" 2
\fBParse:\fP Comprueba que el parseo del comando LIST sea correcto\&. 
.PP
.PP
Una vez realizadas las comprobaciones, dicha función se ejecuta con el siguiente flujo:
.PP
.PD 0
.IP "\(bu" 2
\fBRecupera la lista de canales:\fP Es decir, solicita un array de canales al TAD utilizando la función \fBIRCTADChan_GetList\fP a la que se le pasan los parámetros \fBchar *** channels\fP y \fBint *size\fP para tener los datos\&.  
.IP "\(bu" 2
\fBDevuelve mensaje de inicio:\fP Es decir, se devuelve al usuario un mensaje generado por la función del TAD \fBIRCMsg_RplListStart\fP utilizando el descriptor del socket del cliente y la función \fBsend()\fP\&. 
.IP "\(bu" 2
\fBGenera la lista de canales:\fP Es decir, se devuelve al usuario la lista de canales utilizando el descriptor del socket del cliente y la función \fBsend()\fP\&. Para ello, se realizan el siguiente flujo sobre la lista adquirida de canales: 
.PD 0

.IP "  \(bu" 4
\fBComprobación del modo del canal:\fP Antes de enviar el canal se comprueba el modo, únicamente se enviará la lista de canales que sean públicos, nunca los secretos\&. 
.IP "  \(bu" 4
\fBNombre del canal:\fP Se devuelve el nombre del canal\&. 
.IP "  \(bu" 4
\fBNúmero de usuarios:\fP Junto al nombre del canal se devuelve el número de usuarios que están en ese momento en el canal\&. 
.IP "  \(bu" 4
\fBTopic del canal:\fP Junto al nombre del canal y el número de usuarios, se devuelve también el topic del canal actual\&. 
.PP

.IP "\(bu" 2
\fBDevuelve mensaje de fin:\fP Es decir, se devuelve al usuario un mensaje generado por la función del TAD \fBIRCMsg_RplListEnd\fP indicándole que se ha finalizado con la comunicación de la lista de canales\&. 
.PP
.PP
Al finalizar el flujo de la función se liberan los recursos utilizados\&.
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBvoid\fP No devuelve nada\&. 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

