.TH "thread_args" 3 "Lunes, 13 de Marzo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_args \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <G-2313-06-P1_thread_pool\&.h>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "struct \fBthread_pool_t\fP * \fBpool\fP"
.br
.ti -1c
.RI "struct \fBthread_t\fP * \fBcurrent\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 63 del archivo G-2313-06-P1_thread_pool\&.h\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "struct \fBthread_t\fP* thread_args::current"

.PP
Definición en la línea 65 del archivo G-2313-06-P1_thread_pool\&.h\&.
.SS "struct \fBthread_pool_t\fP* thread_args::pool"

.PP
Definición en la línea 64 del archivo G-2313-06-P1_thread_pool\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes de Comunicaciones II del código fuente\&.
