.TH "recibir_datos_SSL" 3 "Domingo, 7 de Mayo de 2017" "Version 1.0" "Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recibir_datos_SSL \- Recepción de datos vía SSL 

.SH "Synopsis"
.PP
\fC \fB#include\fP \fB<\fBG-2313-06-P3_ssl\&.h\fP>\fP 
.br
 \fBint \fBrecibir_datos_SSL(SSL * ssl, char *buf)\fP;\fP \fP 
.SH "Descripción"
.PP
Recibe un buffer de datos recibidos como parámetros mediante la conexión SSL recibida también como parámetro\&. 
.br
.SS "\fBFunciones de librería SSL:\fP"
.PP
.PD 0
.IP "\(bu" 2
SSL_read(); 
.PP
.SH "Valores devueltos"
.PP
.PD 0
.IP "\(bu" 2
\fBint\fP Valor entero que representa una aceptación correcta/incorrecta 
.PP
.SH "Autores"
.PP
.PD 0
.IP "\(bu" 2
Jorge Parrilla Llamas (jorge.parrilla@estudiante.uam.es) 
.IP "\(bu" 2
Javier de Marco Tomás (javier.marco@estudiante.uam.es) 
.PP

